// CommonJS, every file is module (by default)
// Modules, Encapsulated Code (only share minimum)
const names = require("./4-names")
const SayHi = require("./5-utils")
const data = require("./6-alternative-flavor")
const memory = require("./7-mind-grenade")

SayHi('susan')
SayHi(names.peter)
SayHi(names.john)